# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f990803a842049f2482b8ffac8457658c10fe1512e8d5d1d0ea8b585fc69891df88b5eab80b9470dd969324abe6be40fbfb4e0406ad01cb723951b996f1c7d36

test:
  secret_key_base: 15f80d10b746fab3184b08f19d4fb4a07fbff1b2f364f79fddd3257319fdf68bbd6a8899e6a619c1be72bd6446c747907e29b286752853d604997c8e391331db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
